# Generated by Django 4.2 on 2024-03-10 17:32

from django.db import migrations, models
import students.utils


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_id',
            field=models.CharField(default=students.utils.create_new_stu_id, editable=False, max_length=50, unique=True),
        ),
    ]
