# Generated by Django 4.2 on 2024-03-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_company'),
        ('students', '0002_student_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='company',
        ),
        migrations.AddField(
            model_name='student',
            name='company',
            field=models.ManyToManyField(to='accounts.company'),
        ),
    ]
