# Generated by Django 4.2 on 2024-03-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_stu_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='student',
            name='contact_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
