# Generated by Django 4.2 on 2024-03-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
